<a href="https://colab.research.google.com/github/donlee4u/ML_Class/blob/main/3%EC%A3%BC%EC%B0%A8_Python_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])

In [ ]:
a

In [ ]:
a[0]

In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
 b[0][2]

np.int64(3)

In [ ]:
a = np.array([[ 0, 1, 2],
 		[ 3, 4, 5],
		[ 6, 7, 8]])

In [ ]:
a.shape

(3, 3)

In [ ]:
a.ndim

2

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.itemsize

8

In [ ]:
a.size

9

In [ ]:
np.zeros( (3, 4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones( (3, 4), dtype=np.int32 )

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
x = np.ones(5, dtype=np.int64)

In [ ]:
x

array([1, 1, 1, 1, 1], dtype=int64)

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(1, 6)

array([1, 2, 3, 4, 5])

In [ ]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(0, 10, 100)

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [ ]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x = np.array([[1, 2], [3, 4]])

In [ ]:
y = np.array([[5, 6], [7, 8]])

In [ ]:
np.concatenate((x, y), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
np.vstack((x, y))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.hstack((x, y))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
a = np.arange(12)

In [ ]:
a.shape

(12,)

In [ ]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a.reshape(6, -1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
array = np.arange(30).reshape(-1, 10)

In [ ]:
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
arr1, arr2 = np.split(array, [3], axis=1)

In [ ]:
arr1

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [ ]:
arr2

array([[ 3,  4,  5,  6,  7,  8,  9],
       [13, 14, 15, 16, 17, 18, 19],
       [23, 24, 25, 26, 27, 28, 29]])

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])


In [ ]:
a.shape

(6,)

In [ ]:
a1 = a[np.newaxis, :]

In [ ]:
a1

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
a1.shape

(1, 6)

In [ ]:
a2 = a[:, np.newaxis]

In [ ]:
a2.shape

(6, 1)

In [ ]:
ages = np.array([18, 19, 25, 30, 28])

In [ ]:
ages[1:3]

array([19, 25])

In [ ]:
ages[:2]

array([18, 19])

In [ ]:
y = ages > 20

In [ ]:
y

array([False, False,  True,  True,  True])

In [ ]:
ages[ ages > 20 ]

array([25, 30, 28])

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
a[0, 2]

3

In [ ]:
a[0, 0] = 12

In [ ]:
a

array([[12,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
a[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [ ]:
arr1 = np.array([[1, 2], [3, 4], [5, 6]])

In [ ]:
arr2 = np.array([[1, 1], [1, 1], [1, 1]])

In [ ]:
result = arr1 + arr2

In [ ]:
result

array([[2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
miles = np.array([1, 2, 3])

In [ ]:
result = miles * 1.6

In [ ]:
result

array([1.6, 3.2, 4.8])

In [ ]:
arr1 = np.array([[1, 2], [3, 4], [5, 6]])

In [ ]:
arr2 = np.array([[2, 2], [2, 2], [2, 2]])

In [ ]:
result = arr1 * arr2

In [ ]:
result

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
arr2 = np.array([[2, 2], [2, 2], [2, 2]])

In [ ]:
result = arr1 @ arr2

In [ ]:
result

array([[12, 12],
       [30, 30],
       [48, 48]])

In [ ]:
A = np.array([0, 1, 2, 3])


In [ ]:
10 * np.sin(A)

array([0.        , 8.41470985, 9.09297427, 1.41120008])

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
a.sum()

45

In [ ]:
a.min()

1

In [ ]:
a.max()

9

In [ ]:
scores = np.array([[99, 93, 60], [98, 82, 93],
               [93, 65, 81], [78, 82, 81]])

In [ ]:
scores.mean(axis=0)

array([92.  , 80.5 , 78.75])

In [ ]:
np.random.seed(100)


In [ ]:
np.random.rand(5)


array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [ ]:
np.random.rand(5, 3)


array([[0.12156912, 0.67074908, 0.82585276],
       [0.13670659, 0.57509333, 0.89132195],
       [0.20920212, 0.18532822, 0.10837689],
       [0.21969749, 0.97862378, 0.81168315],
       [0.17194101, 0.81622475, 0.27407375]])

In [ ]:
np.random.randn(5)

array([ 0.67272081, -0.10441114, -0.53128038,  1.02973269, -0.43813562])

In [ ]:
np.random.randn(5, 4)

array([[-1.11831825,  1.61898166,  1.54160517, -0.25187914],
       [-0.84243574,  0.18451869,  0.9370822 ,  0.73100034],
       [ 1.36155613, -0.32623806,  0.05567601,  0.22239961],
       [-1.443217  , -0.75635231,  0.81645401,  0.75044476],
       [-0.45594693,  1.18962227, -1.69061683, -1.35639905]])

In [ ]:
m, sigma = 10, 2

In [ ]:
m + sigma*np.random.randn(5)

array([ 7.53513097,  8.91112168,  8.66365653, 10.01462913,  8.77412253])

In [ ]:
mu, sigma = 0, 0.1 	# 평균과 표준 편차

In [ ]:
np.random.normal(mu, sigma, 5)

array([ 0.12997481, -0.17330956, -0.09833101,  0.03575078, -0.16135785])

In [ ]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [ ]:
unique_values = np.unique(a)

In [ ]:
unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr.T)

[[1 3 5]
 [2 4 6]]


In [ ]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
x.flatten()

array(['KR', 'Korea', 98480, 'Seoul', 48422644, 'US', 'USA', 9629091,
       'Washington', 310232863, 'JP', 'Japan', 377835, 'Tokyo', 127288000,
       'CN', 'China', 9596960, 'Beijing', 1330044000, 'RU', 'Russia',
       17100000, 'Moscow', 140702000], dtype=object)

# CSV 파일

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import numpy as np
import pandas as pd

x = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/countries.csv', header=0).values
print(x)

[['KR' 'Korea' 98480 'Seoul' 48422644]
 ['US' 'USA' 9629091 'Washington' 310232863]
 ['JP' 'Japan' 377835 'Tokyo' 127288000]
 ['CN' 'China' 9596960 'Beijing' 1330044000]
 ['RU' 'Russia' 17100000 'Moscow' 140702000]]


In [ ]:
x = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/countries.csv', usecols=['country','capital']).values
print(x)

[['Korea' 'Seoul']
 ['USA' 'Washington']
 ['Japan' 'Tokyo']
 ['China' 'Beijing']
 ['Russia' 'Moscow']]


In [ ]:
a = np.arange(100,116,1).reshape(4,4)
df = pd.DataFrame(a)
print(df)

     0    1    2    3
0  100  101  102  103
1  104  105  106  107
2  108  109  110  111
3  112  113  114  115


In [ ]:
df.to_csv('/content/drive/MyDrive/Colab Notebooks/pd.csv')

# Matplotlib

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

X = [ "Mon", "Tue", "Wed", "Thur", "Fri",  "Sat", "Sun" ]
Y1 = [15.6, 14.2, 16.3, 18.2, 17.1, 20.2, 22.4]
Y2 = [20.1, 23.1, 23.8, 25.9, 23.4, 25.1, 26.3]

plt.plot(X, Y1, label="Seoul")		# 분리시켜서 그려도 됨
plt.plot(X, Y2, label="Busan")		# 분리시켜서 그려도 됨
plt.xlabel("day")
plt.ylabel("temperature")
plt.legend(loc="upper left")
plt.title("Temperatures of Cities")
plt.show()

In [ ]:
import matplotlib.pyplot as plt

plt.plot([1,1,1,1],linestyle='',color='b',marker='o',)
plt.plot([2,2,2,2],linestyle='',color='r',marker='.')
plt.plot([3,3,3,3],linestyle='',color='y',marker='v')
plt.plot([4,4,4,4],linestyle='',color='k',marker='^')
plt.plot([5,5,5,5],linestyle='',color='g',marker='s')
plt.plot([6,6,6,6],color='blue',marker='P')
plt.plot([7,7,7,7],color='red',marker='+')
plt.plot([8,8,8,8],color='yellow',marker='x')
plt.plot([9,9,9,9],color='black',marker='D')

plt.show()

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

X = [ "Mon", "Tue", "Wed", "Thur", "Fri",  "Sat", "Sun" ]
plt.plot(X, [15.6, 14.2, 16.3, 18.2, 17.1, 20.2, 22.4], "sm")
plt.show()

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

X = [ "Mon", "Tue", "Wed", "Thur", "Fri",  "Sat", "Sun" ]
Y = [15.6, 14.2, 16.3, 18.2, 17.1, 20.2, 22.4]
plt.bar(X, Y)
plt.show()


In [ ]:
import matplotlib.pyplot as plt
import numpy as np

numbers = np.random.normal(size=10000)

plt.hist(numbers)
plt.xlabel("value")
plt.ylabel("freq")
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
X = np.arange(0, 10)
Y = X**2
plt.plot(X, Y)
plt.show()

In [ ]:
X = np.arange(0, 10)
Y1 = np.ones(10)
Y2 = X
Y3 = X**2
plt.plot(X, Y1, X, Y2, X, Y3)
plt.show()

In [ ]:
# Sigmoid function
import matplotlib.pyplot as plt
import numpy as np
import math

X = np.linspace(-10, 10, 100)
Y = 1/(1 + np.exp(-X))

plt.plot(X, Y)
plt.xlabel("x")
plt.ylabel("Sigmoid(X)")
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

def sigmoid(x):
    s=1/(1+np.exp(-x))
    ds=s*(1-s)  		# 시그모이드 함수 1차 미분 함수
    return s,ds

X = np.linspace(-10, 10, 100)
Y1, Y2 = sigmoid(X)

plt.plot(X, Y1, X, Y2)
plt.xlabel("x")
plt.ylabel("Sigmoid(X), Sigmoid'(X)")
plt.show()

In [ ]:
# Compute the x and y coordinates for points on a sine curve
import matplotlib.pyplot as plt
%matplotlib inline

x = np.arange(0,3*np.pi,0.1)
y = np.sin(x)

# Plot the points using matplotlib
plt.plot(x, y)
plt.show()

In [ ]:
y_sin = np.sin(x)
y_cos = np.cos(x)

# Plot the points using matplotlib
plt.plot(x, y_sin)
plt.plot(x, y_cos)

plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])
plt.axis('tight')  # 모든 데이터를 볼 수 있게 축의 범위를 크게 설정
plt.show()

In [ ]:
# Compute the x and y coordinates for points on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)
y_tan = np.tan(x)

# Set up a subplot grid that has height 2 and width 1,
# and set the first such subplot as active.
plt.subplot(3, 1, 1)   # same as plt.subplot(211)

# Make the first plot
plt.plot(x, y_sin)
plt.axis('tight')
plt.title('Sine')

# Set the second subplot as active, and make the second plot.
plt.subplot(3, 1, 2)    # same as plt.subplot(212)
plt.plot(x, y_cos)
plt.axis('tight')
plt.title('Cosine')

# Set the third subplot as active, and make the third plot.
plt.subplot(3, 1, 3)    # same as plt.subplot(213)
plt.plot(x, y_tan)
plt.axis('tight')
plt.title('Tangent')

# Show the figure.
plt.show()


In [ ]:
# Compute the x and y coordinates for points on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)
y_tan = np.tan(x)

# Set up a subplot grid that has height 2 and width 1,
# and set the first such subplot as active.
plt.subplot(2, 2, 1)   # same as plt.subplot(211)

# Make the first plot
plt.plot(x, y_sin)
plt.axis('tight')
plt.title('Sine')

# Set the second subplot as active, and make the second plot.
plt.subplot(2, 2, 2)    # same as plt.subplot(212)
plt.plot(x, y_cos)
plt.axis('tight')
plt.title('Cosine')

# Set the third subplot as active, and make the third plot.
plt.subplot(2, 2, 4)    # same as plt.subplot(213)
plt.plot(x, y_tan)
plt.axis('tight')
plt.title('Tangent')

# Show the figure.
plt.show()

# 3주차 과제

In [ ]:
import numpy as np
arr = np.arange(0, 10)
arr = arr[::-1]
print(arr)

In [ ]:
import numpy as np
a = np.arange(0,9).reshape((3, 3))
print(a)
b = np.arange(0,9).reshape((9, 1))
print(b)

In [ ]:
import numpy as np
a = np.ones((10,10))
a[1:-1,1:-1] = 0
print(a)

In [ ]:
import numpy as np
a = np.zeros((5, 5),dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

In [ ]:
import numpy as np
x = np.arange(10)
print(x)
x[(x >= 5) & (x <= 8)] *= -1
print(x)

In [ ]:
import numpy as np
x = np.array([[4, 5],[7, 10]])
y = np.array([[2, 3],[1, 5]])
print("원본 벡터:")
print(x)
print(y)
print("벡터의 내적:", np.dot(x, y))

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

def sigmoid(x):
    s=1/(1+np.exp(-x))
    ds=s*(1-s)  		# 시그모이드 함수 1차 미분 함수
    return s,ds

X = np.linspace(-10, 10, 100)
Y1, Y2 = sigmoid(X)

plt.plot(X, Y1, X, Y2)
plt.xlabel("x")
plt.ylabel("Sigmoid(X), Sigmoid'(X)")
plt.show()

# 선형방정식 풀기


- 선형 연립방정식 (two equations, two unknowns)
$$
\begin{align*}
4x_{1} - 5x_{2} &= -13\\
-2x_{1} + 3x_{2} &= 9
\end{align*}
$$

- 벡터 형식 ; $Ax = b$,
<br>
$$A =
\begin{bmatrix}
4 & -5 \\
-2 & 3
\end{bmatrix}
, \quad
x =
\begin{bmatrix}
x_{1} \\
x_{2}
\end{bmatrix}
, \quad
b =
\begin{bmatrix}
-13 \\
9
\end{bmatrix}
$$
<br>
- 역행렬
$$
\begin{align*}
Ax &= b \\
A^{-1}Ax &= A^{-1}b \\
x &= A^{-1}b
\end{align*}
$$
<br>

In [ ]:
import numpy as np

In [ ]:
A = np.array([[4, -5], [-2, 3]])
print(A)

[[ 4 -5]
 [-2  3]]


In [ ]:
# b = np.array([-13, 9])
b = np.array([[-13], [9]])
print(b)

[[-13]
 [  9]]


<br>
$A^{-1} b$
<br>

In [ ]:
x = np.linalg.inv(A)
print(x)

[[1.5 2.5]
 [1.  2. ]]


In [ ]:
x = np.linalg.inv(A).dot(b)
print(x)

[[3.]
 [5.]]


In [ ]:
A = np.asmatrix(A)   # Data A를 행렬로 변환
b = np.asmatrix(b)   # Data b를 행렬로 변환
print(A)
print(b)

[[ 4 -5]
 [-2  3]]
[[-13]
 [  9]]


In [ ]:
x = A.I*b
print(x)

[[3.]
 [5.]]


# Vector-Vector Products

- 내적(Inner product): $x, y \in \mathbb{R}^{n}$

$$\langle x,y \rangle = x^{T}y = \sum\limits_{i=1}^{n}x_{i}\,y_{i} \quad \in \mathbb{R}$$


In [ ]:
x = np.array([[1],
              [1]])

y = np.array([[2],
              [3]])

print(x.T.dot(y))

[[5]]


In [ ]:
x = np.asmatrix(x)
y = np.asmatrix(y)

print(x.T*y)

[[5]]



# Norms (벡터의 크기)


Norm provides a general concept of distance in linear algebra.

- $l_{2}$ norm
$$\left\lVert x \right\rVert _{2} = \sqrt{\sum\limits_{i=1}^{n}x_{i}^2}$$

- $l_{1}$ norm

$$\left\lVert x \right\rVert _{1} = \sum\limits_{i=1}^{n} \left\lvert x_{i} \right\rvert$$

- $l_p$ norm

$$\|x\|_p = \left( \sum_{i=1}^{n} |x_i|^p \right)^{\frac{1}{p}}$$

- $l_{\infty}$ norm

$$\|x\|_{\infty} = \max_{i} |x_i|$$




In [ ]:
x = np.array([[4],
              [3]])
print(x)

[[4]
 [3]]


In [ ]:
z = np.linalg.norm(x, 2)  # L2 norm
# z = np.linalg.norm(x)
print(z)

5.0


In [ ]:
z = np.linalg.norm(x, 1)  # L1 norm
print(z)

7.0
