In [1]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])

In [ ]:
a

array([1, 2, 3])

In [ ]:
a[0]

1

In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
 b[0][2]

3

In [ ]:
a = np.array([[ 0, 1, 2],
 		[ 3, 4, 5],
		[ 6, 7, 8]])

In [ ]:
a.shape

(3, 3)

In [ ]:
a.ndim

2

In [ ]:
a.dtype

dtype('int32')

In [ ]:
a.itemsize

4

In [ ]:
a.size

9

In [ ]:
np.zeros( (3, 4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones( (3, 4), dtype=np.int32 )

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
x = np.ones(5, dtype=np.int64)

In [ ]:
x

array([1, 1, 1, 1, 1], dtype=int64)

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(1, 6)

array([1, 2, 3, 4, 5])

In [ ]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(0, 10, 100)

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [ ]:
np.sort(arr)

In [ ]:
x = np.array([[1, 2], [3, 4]])

In [ ]:
y = np.array([[5, 6], [7, 8]])

In [ ]:
np.concatenate((x, y), axis=1)

In [ ]:
np.vstack((x, y))

In [ ]:
np.hstack((x, y))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
a = np.arange(12)

In [ ]:
a.shape

(12,)

In [ ]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a.reshape(6, -1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
array = np.arange(30).reshape(-1, 10)

In [ ]:
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
arr1, arr2 = np.split(array, [3], axis=1)

In [ ]:
arr1

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [ ]:
arr2

array([[ 3,  4,  5,  6,  7,  8,  9],
       [13, 14, 15, 16, 17, 18, 19],
       [23, 24, 25, 26, 27, 28, 29]])

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])


In [ ]:
a.shape

(6,)

In [ ]:
a1 = a[np.newaxis, :]

In [ ]:
a1

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
a1.shape

(1, 6)

In [ ]:
a2 = a[:, np.newaxis]

In [ ]:
a2.shape

(6, 1)

In [ ]:
ages = np.array([18, 19, 25, 30, 28])

In [ ]:
ages[1:3]

array([19, 25])

In [ ]:
ages[:2]

array([18, 19])

In [ ]:
y = ages > 20

In [ ]:
y

array([False, False,  True,  True,  True])

In [ ]:
ages[ ages > 20 ]

array([25, 30, 28])

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
a[0, 2]

3

In [ ]:
a[0, 0] = 12

In [ ]:
a

array([[12,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
a[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [ ]:
arr1 = np.array([[1, 2], [3, 4], [5, 6]])

In [ ]:
arr2 = np.array([[1, 1], [1, 1], [1, 1]])

In [ ]:
result = arr1 + arr2

In [ ]:
result

array([[2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
miles = np.array([1, 2, 3])

In [ ]:
result = miles * 1.6

In [ ]:
result

array([1.6, 3.2, 4.8])

In [ ]:
arr1 = np.array([[1, 2], [3, 4], [5, 6]])

In [ ]:
arr2 = np.array([[2, 2], [2, 2], [2, 2]])

In [ ]:
result = arr1 * arr2

In [ ]:
result

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

# 행렬 내적 곱셈

In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
arr2 = np.array([[2, 2], [2, 2], [2, 2]])

In [ ]:
result = arr1 @ arr2
result

array([[12, 12],
       [30, 30],
       [48, 48]])

In [ ]:
result2 = arr1.dot(arr2)
result2

array([[12, 12],
       [30, 30],
       [48, 48]])

# 함수

In [ ]:
A = np.array([0, 1, 2, 3])
10 * np.sin(A)

array([0.        , 8.41470985, 9.09297427, 1.41120008])

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
a.sum()

45

In [ ]:
a.min()

1

In [ ]:
a.max()

9

In [ ]:
scores = np.array([[99, 93, 60], [98, 82, 93],
               [93, 65, 81], [78, 82, 81]])

In [ ]:
scores.mean(axis=0)

array([92.  , 80.5 , 78.75])

In [ ]:
scores.mean(axis=1)

array([84.        , 91.        , 79.66666667, 80.33333333])

# 난수 생성

In [9]:
np.random.seed(100)

In [13]:
np.random.rand(5)

array([0.37283205, 0.00568851, 0.25242635, 0.79566251, 0.01525497])

In [11]:
np.random.rand(5, 3)

array([[0.12156912, 0.67074908, 0.82585276],
       [0.13670659, 0.57509333, 0.89132195],
       [0.20920212, 0.18532822, 0.10837689],
       [0.21969749, 0.97862378, 0.81168315],
       [0.17194101, 0.81622475, 0.27407375]])

In [15]:
np.random.randint(1, 7, size=10)

array([3, 6, 3, 2, 1, 6, 3, 2, 6, 5])

In [ ]:
np.random.randn(5)

array([ 0.18451869,  0.9370822 ,  0.73100034,  1.36155613, -0.32623806])

In [ ]:
np.random.randn(5, 4)

array([[ 0.05567601,  0.22239961, -1.443217  , -0.75635231],
       [ 0.81645401,  0.75044476, -0.45594693,  1.18962227],
       [-1.69061683, -1.35639905, -1.23243451, -0.54443916],
       [-0.66817174,  0.00731456, -0.61293874,  1.29974807],
       [-1.73309562, -0.9833101 ,  0.35750775, -1.6135785 ]])

In [16]:
m, sigma = 10, 2

In [17]:
m + sigma*np.random.randn(5)

array([13.07145324, 10.50999545,  8.3116855 ,  8.03411308,  9.38780434])

In [ ]:
mu, sigma = 0, 0.1 	# 평균과 표준 편차

In [ ]:
np.random.normal(mu, sigma, 5)

array([ 0.12997481, -0.17330956, -0.09833101,  0.03575078, -0.16135785])

# 고유항목

In [ ]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [ ]:
unique_values = np.unique(a)

In [ ]:
unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# 전치(Transpose) 행렬

In [27]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
print(arr.T)

[[1 3 5]
 [2 4 6]]


In [30]:
np.transpose(arr)

array([[1, 3, 5],
       [2, 4, 6]])

# 배열 평탄화(Flatten)

In [31]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [32]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# CSV 파일 읽고 쓰기

In [38]:
import numpy as np
import pandas as pd

# x = pd.read_csv('countries.csv', header=0).values
# print(x)

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

X = [ "Mon", "Tue", "Wed", "Thur", "Fri",  "Sat", "Sun" ]
Y1 = [15.6, 14.2, 16.3, 18.2, 17.1, 20.2, 22.4]
Y2 = [20.1, 23.1, 23.8, 25.9, 23.4, 25.1, 26.3]

plt.plot(X, Y1, label="Seoul")		# 분리시켜서 그려도 됨
plt.plot(X, Y2, label="Busan")		# 분리시켜서 그려도 됨
plt.xlabel("day")
plt.ylabel("temperature")
plt.legend(loc="upper left")
plt.title("Temperatures of Cities")
plt.show()

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

X = [ "Mon", "Tue", "Wed", "Thur", "Fri",  "Sat", "Sun" ]
plt.plot(X, [15.6, 14.2, 16.3, 18.2, 17.1, 20.2, 22.4], "sm")
plt.show()

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

X = [ "Mon", "Tue", "Wed", "Thur", "Fri",  "Sat", "Sun" ]
Y = [15.6, 14.2, 16.3, 18.2, 17.1, 20.2, 22.4]
plt.bar(X, Y)
plt.show()


In [ ]:
import matplotlib.pyplot as plt
import numpy as np

numbers = np.random.normal(size=10000)

plt.hist(numbers)
plt.xlabel("value")
plt.ylabel("freq")
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
X = np.arange(0, 10)
Y = X**2
plt.plot(X, Y)
plt.show()

In [ ]:
X = np.arange(0, 10)
Y1 = np.ones(10)
Y2 = X
Y3 = X**2
plt.plot(X, Y1, X, Y2, X, Y3)
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import math

X = np.linspace(-10, 10, 100)
Y = 1/(1 + np.exp(-X))

plt.plot(X, Y)
plt.xlabel("x")
plt.ylabel("Sigmoid(X)")
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

def sigmoid(x):
    s=1/(1+np.exp(-x))
    ds=s*(1-s)  		# 시그모이드 함수 1차 미분 함수
    return s,ds

X = np.linspace(-10, 10, 100)
Y1, Y2 = sigmoid(X)

plt.plot(X, Y1, X, Y2)
plt.xlabel("x")
plt.ylabel("Sigmoid(X), Sigmoid'(X)")
plt.show()